# Generated by Django 4.1.3 on 2022-11-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'running'), ('BR', 'broken')], max_length=32)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('brake_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата поломки')),
            ],
        ),
    ]
