# Generated by Django 4.1.3 on 2022-11-21 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 11, 21, 7, 17, 18, 168109, tzinfo=datetime.timezone.utc), max_length=254, unique=True, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
