# Generated by Django 4.1.3 on 2022-11-21 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=100)),
                ('y', models.IntegerField(default=100)),
                ('z', models.IntegerField(default=100)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='stations.station', verbose_name='Координаты')),
            ],
        ),
    ]
