version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    env_file:
      - ./space_stations/space/.env
    volumes:
      - ./db:/var/lib/postgresql/data/
  backend:
    image: mvrogozov/space:v1.0
    tty: true
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./space_stations/space/.env
